package beans;

// Generated 25 mai 2013 15:25:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContientId generated by hbm2java
 */
@Embeddable
public class ContientId implements java.io.Serializable {

    private int idFacture;
    private int idProduit;

    public ContientId() {
    }

    public ContientId( int idFacture, int idProduit ) {
        this.idFacture = idFacture;
        this.idProduit = idProduit;
    }

    @Column( name = "id_facture", nullable = false )
    public int getIdFacture() {
        return this.idFacture;
    }

    public void setIdFacture( int idFacture ) {
        this.idFacture = idFacture;
    }

    @Column( name = "id_produit", nullable = false )
    public int getIdProduit() {
        return this.idProduit;
    }

    public void setIdProduit( int idProduit ) {
        this.idProduit = idProduit;
    }

    public boolean equals( Object other ) {
        if ( ( this == other ) )
            return true;
        if ( ( other == null ) )
            return false;
        if ( !( other instanceof ContientId ) )
            return false;
        ContientId castOther = (ContientId) other;

        return ( this.getIdFacture() == castOther.getIdFacture() )
                && ( this.getIdProduit() == castOther.getIdProduit() );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdFacture();
        result = 37 * result + this.getIdProduit();
        return result;
    }

}
