package beans;

// Generated 25 mai 2013 15:25:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table( name = "facture" )
public class Facture implements java.io.Serializable {

    private int           idFacture;
    private Utilisateur   utilisateur;
    private Client        client;
    private Date          dateFacture;
    private Double        montantFacture;
    private String        modePaiementFacture;
    private Set<Contient> contients = new HashSet<Contient>( 0 );

    public Facture() {
    }

    public Facture( int idFacture, Utilisateur utilisateur, Client client ) {
        this.idFacture = idFacture;
        this.utilisateur = utilisateur;
        this.client = client;
    }

    public Facture( int idFacture, Utilisateur utilisateur, Client client, Date dateFacture, Double montantFacture,
            String modePaiementFacture, Set<Contient> contients ) {
        this.idFacture = idFacture;
        this.utilisateur = utilisateur;
        this.client = client;
        this.dateFacture = dateFacture;
        this.montantFacture = montantFacture;
        this.modePaiementFacture = modePaiementFacture;
        this.contients = contients;
    }

    @Id
    @Column( name = "id_facture", unique = true, nullable = false )
    public int getIdFacture() {
        return this.idFacture;
    }

    public void setIdFacture( int idFacture ) {
        this.idFacture = idFacture;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_user", nullable = false )
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur( Utilisateur utilisateur ) {
        this.utilisateur = utilisateur;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_client", nullable = false )
    public Client getClient() {
        return this.client;
    }

    public void setClient( Client client ) {
        this.client = client;
    }

    @Temporal( TemporalType.DATE )
    @Column( name = "date_facture", length = 13 )
    public Date getDateFacture() {
        return this.dateFacture;
    }

    public void setDateFacture( Date dateFacture ) {
        this.dateFacture = dateFacture;
    }

    @Column( name = "montant_facture", scale = 0 )
    public Double getMontantFacture() {
        return this.montantFacture;
    }

    public void setMontantFacture( Double montantFacture ) {
        this.montantFacture = montantFacture;
    }

    @Column( name = "mode_paiement_facture", length = 128 )
    public String getModePaiementFacture() {
        return this.modePaiementFacture;
    }

    public void setModePaiementFacture( String modePaiementFacture ) {
        this.modePaiementFacture = modePaiementFacture;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "facture" )
    public Set<Contient> getContients() {
        return this.contients;
    }

    public void setContients( Set<Contient> contients ) {
        this.contients = contients;
    }

}
