package beans;

// Generated 25 mai 2013 15:25:21 by Hibernate Tools 3.4.0.CR1


import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prixproduit generated by hbm2java
 */
@Entity
@Table( name = "prixproduit" )
public class Prixproduit implements java.io.Serializable {

    private int     idPrix;
    private Produit produit;
    private Date    debutValiditePrix;
    private Date    finValiditePrix;
    private Double  valeurPrix;

    public Prixproduit() {
    }

    public Prixproduit( int idPrix, Produit produit ) {
        this.idPrix = idPrix;
        this.produit = produit;
    }

    public Prixproduit( int idPrix, Produit produit, Date debutValiditePrix, Date finValiditePrix, Double valeurPrix ) {
        this.idPrix = idPrix;
        this.produit = produit;
        this.debutValiditePrix = debutValiditePrix;
        this.finValiditePrix = finValiditePrix;
        this.valeurPrix = valeurPrix;
    }

    @Id
    @Column( name = "idPrix", unique = true, nullable = false )
    public int getIdPrix() {
        return this.idPrix;
    }

    public void setIdPrix( int idPrix ) {
        this.idPrix = idPrix;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "idProduit", nullable = false )
    public Produit getProduit() {
        return this.produit;
    }

    public void setProduit( Produit produit ) {
        this.produit = produit;
    }

    @Temporal( TemporalType.DATE )
    @Column( name = "debut_validite_prix", length = 13 )
    public Date getDebutValiditePrix() {
        return this.debutValiditePrix;
    }

    public void setDebutValiditePrix( Date debutValiditePrix ) {
        this.debutValiditePrix = debutValiditePrix;
    }

    @Temporal( TemporalType.DATE )
    @Column( name = "fin_validite_prix", length = 13 )
    public Date getFinValiditePrix() {
        return this.finValiditePrix;
    }

    public void setFinValiditePrix( Date finValiditePrix ) {
        this.finValiditePrix = finValiditePrix;
    }

    @Column( name = "valeur_prix", scale = 0 )
    public Double getValeurPrix() {
        return this.valeurPrix;
    }

    public void setValeurPrix( Double valeurPrix ) {
        this.valeurPrix = valeurPrix;
    }

}
