package beans;

// Generated 25 mai 2013 15:25:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stockproduit generated by hbm2java
 */
@Entity
@Table( name = "stockproduit" )
public class Stockproduit implements java.io.Serializable {

    private int         idStockProduit;
    private Fournisseur fournisseur;
    private Utilisateur utilisateur;
    private Produit     produit;
    private Integer     qteProduitStocke;

    public Stockproduit() {
    }

    public Stockproduit( int idStockProduit, Fournisseur fournisseur, Utilisateur utilisateur, Produit produit ) {
        this.idStockProduit = idStockProduit;
        this.fournisseur = fournisseur;
        this.utilisateur = utilisateur;
        this.produit = produit;
    }

    public Stockproduit( int idStockProduit, Fournisseur fournisseur, Utilisateur utilisateur, Produit produit,
            Integer qteProduitStocke ) {
        this.idStockProduit = idStockProduit;
        this.fournisseur = fournisseur;
        this.utilisateur = utilisateur;
        this.produit = produit;
        this.qteProduitStocke = qteProduitStocke;
    }

    @Id
    @Column( name = "id_stock_produit", unique = true, nullable = false )
    public int getIdStockProduit() {
        return this.idStockProduit;
    }

    public void setIdStockProduit( int idStockProduit ) {
        this.idStockProduit = idStockProduit;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_fournisseur", nullable = false )
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }

    public void setFournisseur( Fournisseur fournisseur ) {
        this.fournisseur = fournisseur;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_user", nullable = false )
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur( Utilisateur utilisateur ) {
        this.utilisateur = utilisateur;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_produit", nullable = false )
    public Produit getProduit() {
        return this.produit;
    }

    public void setProduit( Produit produit ) {
        this.produit = produit;
    }

    @Column( name = "qte_produit_stocke" )
    public Integer getQteProduitStocke() {
        return this.qteProduitStocke;
    }

    public void setQteProduitStocke( Integer qteProduitStocke ) {
        this.qteProduitStocke = qteProduitStocke;
    }

}
