package beans;

// Generated 25 mai 2013 15:25:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table( name = "utilisateur" )
public class Utilisateur implements java.io.Serializable {

    private int               idUser;
    private String            nomUser;
    private String            prenomUser;
    private String            fonctionUser;
    private String            loginUser;
    private String            mdpUser;
    private Set<Stockproduit> stockproduits = new HashSet<Stockproduit>( 0 );
    private Set<Facture>      factures      = new HashSet<Facture>( 0 );

    public Utilisateur() {
    }

    public Utilisateur( int idUser ) {
        this.idUser = idUser;
    }

    public Utilisateur( int idUser, String nomUser, String prenomUser, String fonctionUser, String loginUser,
            String mdpUser, Set<Stockproduit> stockproduits, Set<Facture> factures ) {
        this.idUser = idUser;
        this.nomUser = nomUser;
        this.prenomUser = prenomUser;
        this.fonctionUser = fonctionUser;
        this.loginUser = loginUser;
        this.mdpUser = mdpUser;
        this.stockproduits = stockproduits;
        this.factures = factures;
    }

    @Id
    @Column( name = "id_user", unique = true, nullable = false )
    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser( int idUser ) {
        this.idUser = idUser;
    }

    @Column( name = "nom_user", length = 128 )
    public String getNomUser() {
        return this.nomUser;
    }

    public void setNomUser( String nomUser ) {
        this.nomUser = nomUser;
    }

    @Column( name = "prenom_user", length = 128 )
    public String getPrenomUser() {
        return this.prenomUser;
    }

    public void setPrenomUser( String prenomUser ) {
        this.prenomUser = prenomUser;
    }

    @Column( name = "fonction_user", length = 128 )
    public String getFonctionUser() {
        return this.fonctionUser;
    }

    public void setFonctionUser( String fonctionUser ) {
        this.fonctionUser = fonctionUser;
    }

    @Column( name = "login_user", length = 128 )
    public String getLoginUser() {
        return this.loginUser;
    }

    public void setLoginUser( String loginUser ) {
        this.loginUser = loginUser;
    }

    @Column( name = "mdp_user", length = 128 )
    public String getMdpUser() {
        return this.mdpUser;
    }

    public void setMdpUser( String mdpUser ) {
        this.mdpUser = mdpUser;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "utilisateur" )
    public Set<Stockproduit> getStockproduits() {
        return this.stockproduits;
    }

    public void setStockproduits( Set<Stockproduit> stockproduits ) {
        this.stockproduits = stockproduits;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "utilisateur" )
    public Set<Facture> getFactures() {
        return this.factures;
    }

    public void setFactures( Set<Facture> factures ) {
        this.factures = factures;
    }

}
